vim.keymap.set("n", "<leader>ss", "<cmd>silent! wa<CR>")
vim.keymap.set("n", "<leader>qq", "<cmd>silent! xa<CR><cmd>qa<CR>")
vim.keymap.set("n", "<leader>j", "<c-w>j")
vim.keymap.set("n", "<leader>k", "<c-w>k")
vim.keymap.set("n", "<leader>l", "<c-w>l")
vim.keymap.set("n", "<leader>h", "<c-w>h")
vim.keymap.set("n", "<leader>r", "*:%s//")
